//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MYPASSWORDS
    {
        public int ID { get; set; }
        public Nullable<int> USERID { get; set; }
        public string NAME { get; set; }
        public string URL { get; set; }
        public Nullable<int> CATEGORYID { get; set; }
        public string USERNAME { get; set; }
        public string PASSWORD { get; set; }
    }
}
