//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PasswordManager.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTPROPERTY
    {
        public int PRODUCTPROPERTYID { get; set; }
        public Nullable<int> PRODUCTID { get; set; }
        public string PROPERTYID { get; set; }
    }
}
